### ISSUE TITLE
HIDA Graduate Schools Meetup

### ISSUE THREAD

**Issue by Irratzo** [FZJ-INM1-BDA/HAICon2024-satellite-events#4]
# Title

**HIDA Graduate Schools Meetup**

 **If you are a school member, thank you for upvoting this issue, leaving a comment, and/or sharing with possibly interested people** 👍 🙏 💬 .

# Description 

An opportunity for members of the [HIDA graduate schools](https://www.helmholtz-hida.de/en/research/our-schools/) to meet and network. The schools are [MarDATA](https://www.mardata.de/), [DASHH](https://www.dashh.org), [HDSLEE](https://www.hds-lee.de/), [HEIBRiDS](https://www.heibrids.berlin/), [HIDSS4Health](https://www.hidss4health.de) and [MUDS](https://www.mu-ds.de/).

The idea is that some of us are going to the AI conference anyway, so why not meet up informally. This could be on-site as well as off-site, such as a restaurant. This issue is just here to find a place and date. Do it [at the satellite events](https://github.com/FZJ-INM1-BDA/HAICon2024-satellite-events/issues/4) on June 11 in Jülich (longer) or [at the unconference](https://github.com/Helmholtz-AI-Matter/HAICON24-unconference/issues/1) on June 12 morning in Düsseldorf (shorter)? If, however, someone wants to organize more than that, feel free to do that.

# Responsible person(s)
_name(s), affiliation, contact information_

| Name | Role | School | Affiliation | Contacts |
| ------ | ---- | ------- | ---------- | -------- |
| Johannes Wasmer | TBD | HDSLEE | [FZJ PGI-1](https://go.fzj.de/pgi-1) | @Irratzo, j dot wasmer at fz-juelich.de, [workplace profile](https://go.fzj.de/wasmer) |

More responsible persons would be found in discussion in this issue thread.

# Stats

- Organizational. TBD.
- Format. Meetup.
- Timeframe. TBD.
- Number of participants. Ca. 5-40.
- Material / requirements. None required.

**Comment by SusanneWenzel** [comment]
Hi @Irratzo, can you please add your name and affiliation as contact information

**Comment by Irratzo** [comment]
@SusanneWenzel Done, thanks.

Propose to deprecate this proposal since HIDA is organizing a similar event the week before already.

https://events.hifis.net/event/1306/

Checking back with [Prologue Day](https://haicon24.de/prologue-at-fzj/) admin for OK. @SusanneWenzel

**Comment by Irratzo** [comment]
Propose to deprecate this proposal since HIDA is organizing a similar event the week before already.

https://events.hifis.net/event/1306/

Checking back with [Prologue Day](https://haicon24.de/prologue-at-fzj/) admin for OK.

**Comment by SusanneWenzel** [comment]
@Irratzo sure, no problem

**Comment by SusanneWenzel** [comment]
closed due to redundant events
