### ISSUE TITLE
LLM4Science Hackathon

### ISSUE THREAD

**Issue by Irratzo** [FZJ-INM1-BDA/HAICon2024-satellite-events#5]
# Title

**LLM4Science Hackathon**

_Connected issues: [Satellite events issue](https://github.com/FZJ-INM1-BDA/HAICon2024-satellite-events/issues/5), [unconference issue](https://github.com/Helmholtz-AI-Matter/HAICON24-unconference/issues/2). Deprecate whichever has been ruled out._

# Description 
_scope, timeline_

A hackathon where researchers can play around with language models (LLMs), apply them to their data of choice, integrate them with their services of interest, etc. Here are some examples of similar hackathons and their outcomes. [1](https://doi.org/10.1039/D3DD00113J), [2](https://www.catalyzex.com/paper/arxiv:2306.06283/code), [3](https://www.cecam.org/workshop-details/1291). Here are some possibly relevant Helmholtz resources. [Blablador](https://helmholtz-blablador.fz-juelich.de/), [OpenGTP-X](https://opengpt-x.de/en/).  Other maybe useful material: [karpathy](https://github.com/karpathy/nn-zero-to-hero), [ethz-llm24](https://rycolab.io/classes/llm-s24/).

# Responsible person(s)
_name(s), affiliation, contact information_

| Name | Role | Affiliation | Contacts |
| ------ | ---- | ---------- | -------- |
| | | | |

See also discussion.

# Format
_e.g., workshop, hackathon, tutorial, hands-on section, ..._

The format would be found in discussion in this issue thread.

# Timeframe
_e.g. half day, full day, ..._

The timeframe and duration would be found in discussion in this issue thread.

One point to determine is whether to do this event at the satellite events on June 11 in Jülich (longer) or at the unconference June 12 morning (shorter). See "connected issues" above.

# Requirements
_e.g., PC teaching room_<br>
_min/max number of attendees_

The requirements would be found in discussion in this issue thread.

**Comment by SusanneWenzel** [comment]
Hi @Irratzo, can you please add your name and affiliation as contact information

**Comment by Irratzo** [comment]
@SusanneWenzel Done, thanks.

**Comment by Irratzo** [comment]
@helenehoffmann has [asked](https://github.com/Helmholtz-AI-Matter/HAICON24-unconference/issues/2#issuecomment-2014579461) 

> Dear Johannes, is it already decided whether this will be part of the satellite day?

Not yet. I will update the status within the next two weeks. So far, it looks bad because 1) I will probably be on leave outside the country at the time of the event, 2) I have asked around a bit but found no-one who would like to help set this up and 3) I am new to LLMs myself. So, all I could probably offer is to search for some suitably looking starter material and get started on that together.

**Comment by helenehoffmann** [comment]
For me that sounds like a good topic for the Unconference. You don't need to come with an answer but can bring a question and hope for people who either know something they want to share or also want to know and you explore together in a group. So, if you do not have this topic as satellite event it would fit really good in the unconference and I would be happy if you could host it.

**Comment by Irratzo** [comment]
Thanks for encouragement, @helenehoffmann. 

I sadly cannot help realizing this LLM4Science Hackathon proposal for the Helmholtz AI conference. Neither at the satellite events nor at the unconference. By now, it is established that I will be outside the country in June for a research visit. My apologies.

I leave this issue open in case someone else is found to take over. Otherwise I suggest admin @SusanneWenzel closes the issue. Thank you.
